# Generated by Django 6.0.1 on 2026-01-08 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('tariff_day', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Тариф день (руб/кВтч)')),
                ('tariff_night', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Тариф ночь')),
                ('avg_sun_hours', models.FloatField(verbose_name='Солнечные часы в год')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=100)),
                ('power_w', models.IntegerField(verbose_name='Мощность (Вт)')),
                ('efficiency', models.FloatField(verbose_name='КПД')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensions', models.CharField(blank=True, help_text='ШхВхТ в мм', max_length=50)),
                ('warranty_years', models.IntegerField(default=25)),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_count', models.IntegerField(default=10)),
                ('monthly_consumption', models.FloatField(verbose_name='Потребление (кВтч/мес)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('system_power_kw', models.FloatField(blank=True, null=True, verbose_name='Мощность системы (кВт)')),
                ('yearly_production_kwh', models.FloatField(blank=True, null=True, verbose_name='Выработка (кВтч/год)')),
                ('yearly_saving', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payback_years', models.FloatField(blank=True, null=True)),
                ('co2_saved_kg', models.FloatField(blank=True, null=True, verbose_name='Сэкономлено CO2 (кг/год)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.region')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.solarpanel')),
            ],
            options={
                'verbose_name': 'Расчет',
                'verbose_name_plural': 'Расчеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
